### ISSUE TITLE
config.sh: No such file or directory when running docker compose up

### ISSUE THREAD

**Issue by AntheSevenants** [CentreForDigitalHumanities/tscan#69]
I cloned the repository and ran `docker compose up`. Unfortunately, the build process errors at this stage:

```
 => ERROR [ 5/13] RUN bash config.sh                                                                   0.4s
------
 > [ 5/13] RUN bash config.sh:
#0 0.428 bash: config.sh: No such file or directory
------
failed to solve: process "/bin/sh -c bash config.sh" did not complete successfully: exit code: 127
```

I see that [config.sh is part of .gitignore](https://github.com/UUDigitalHumanitieslab/tscan/blob/master/docker/deployment/.gitignore), so it doesn't ship with the repository. Is any input required on my part, or is this an oversight?

Thanks in advance!

**Comment by oktaal** [comment]
https://github.com/UUDigitalHumanitieslab/tscan/blob/master/docker/deployment/config-example.sh contains a file to copy into the same directory as `config.sh`. I wouldn't depend _too much_ on this way of running things as it's going to be replaced because it's currently dependent on lamachine (#70). (It will still use Docker)

**Comment by AntheSevenants** [comment]
Thanks! I assumed I could just run `docker compose up` since there wasn't any mention of configuration. I'll be keeping an eye out for the new deployment 🙂. Thanks again
