### ISSUE TITLE
Pin versions of dependencies

### ISSUE THREAD

**Issue by oktaal** [CentreForDigitalHumanities/tscan#86]
Allow versions to be pinned using some straightforward format. Eg a list of packages and commit hashes. Help prevent issues such as #85

**Comment by proycon** [comment]
On Mon Oct 9, 2023 at 11:45 AM CEST, Sheean Spoel wrote:
> Allow versions to be pinned using some straightforward format. Eg a list of packages and commit hashes. Help prevent issues such as #85 

I would also recommend to stick to releases, at least for production
scenarios, rather than taking the latest git master branch.

For instance, see https://github.com/LanguageMachines/frog/blob/master/build-deps.sh
for a shell script that installs the latest releases of all Frog dependencies.
